name: Probar PDF

on:
  workflow_dispatch:

jobs:
  probar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar librerías
        run: |
          pip install pdfplumber

      - name: Leer PDF
        run: python generar_csv.py
